#' Simple dead-reckoned track (pseudo-track) estimation based on speed and bodypointing angle. 
#'
#' @description Possible input combinations: ptrack(A,M,s,fs) if A and M are matrices, ptrack(A,M,s,fs,fc) if A and M are matrices, ptrack(A,M,s) if A and M are lists, ptrack(A,M,s,fc = fc) if A and M are lists.
#' @param A An nx3 acceleration matrix with columns [ax ay az] or acceleration sensor list (e.g., from readtag.R). Acceleration can be in any consistent unit, e.g., g or m/s^2. 
#' @param M The magnetometer signal matrix, M = [mx,my,mz] in any consistent unit (e.g., in uT or Gauss)  or magnetometer sensor list (e.g., from readtag.R). A and M must have the same size (and so are both measured at the same sampling rate).
#' @param s The forward speed of the animal in m/s. s can be a single number meaning that the animal is assumed to travel at a constant speed. s can also be a vector with the same number of rows as A and M, e.g., generated by speed_from_depth().
#' @param fs The sampling rate of the sensor data in Hz (samples per second).
#' @param fc (optional) The cut-off frequency of a low-pass filter to aply to A and M before computing bodypointing angle. The filter cut-off frequency is in Hz. The filter length is 4*fs/fc. Filtering adds no group delay. If fc is empty or not given, the default value of 0.2 Hz (i.e., a 5 second time constant) is used.
#' @param include_pe A conditional statement. If include_pe is TRUE, the estimated depth of altitude predicted will be returned with the estimated track.
#' @return T The estimated track in a local level frame. The track is defined as meters of northward and eastward movement (termed 'northing' and 'easting', i.e, T=[northing,easting]) relative to the animal'sposition at the start of the measurements  (which is defined as [0,0]). The track sampling rate is the same as for the input data and so each row of T defines the track coordinates at times 0,1/fs,2/fs,... relative to the start time of the measurements.
#' @return pe The estimated depth or altitude predicted from the speed and pitch angle. This can be compared against the measured depth/altitude to assess errors in the dead-reckoned track. Note that even if pe matches the observed depth, this does not guarantee that the track is accurate.
#' @note Frame: This function assumes a [north,east,up] navigation frame and a [forward,right,up] local frame. Both A and M must be rotated if needed to match the animal's cardinal axes otherwise the track will not be meaningful.
#' @note CAUTION: dead-reckoned tracks are usually very inaccurate. They are useful to get an idea of HOW animals move rather than WHERE they go. Few animals probably travel in exactly the direction of their longitudinal axis and anyway measuring the precise orientation of the longitudinal axis of a non-rigid animal is fraught with error. Moreover, if there is net flow in the medium, the animal will be affected by the flow in addition to its autonomous movement. For swimming animals this can lead to substantial errors. The forward speed is assumed to be with respect to the medium so the track derived here is NOT the 'track-made-good', i.e., the geographic movement of the animal. It estimates the movement of the animal with respect to the medium. There are numerous other sources of error so use at your own risk!
#' @export
#' @example A <- matrix(c(1, -0.5, 0.1, 0.8, -0.2, 0.6, 0.5, -0.9, -0.7), byrow = TRUE, nrow = 3)
#'          M <- matrix(c(1.1, -0.3, 0.5, 0.2, -0.7, 0.5, -0.4, -0.1, 0.2), byrow = TRUE, nrow = 3)
#'          ptrack(A, M, s = 2, fs = 5, fc = NULL, p = NULL, LPF = NULL, include_S = NULL, include_pe = NULL)

ptrack <- function(A, M, s, fs, fc = NULL, include_pe = NULL) {
  #input checks----------------------------------------------------------
  if (nargs() < 3) {
    stop("Inputs for A, M, and s are all required.")
  }
  if (is.list(M) & is.list(A)) {
    if (nargs() > 3) {
      fc <- fs
    }
    if (A$fs != M$fs) {
      stop("A and M must be at the same sampling rate")
    }
    fs <- M$fs
    M <- M$data
    A <- A$data
  } else {
    if (missing(fs)) {
      stop("Inputs for A, M, s, and fs are all required if A and M are matrices")
    }
    if (is.null(fc)) {
      fc <- c()
    }
  }
  if (is.null(fc) == TRUE) {
    fc <- 0.2
  }
  if (is.null(include_pe) == TRUE) {
    include_pe <- FALSE
  }
  nf <- 4 * fs / fc
  A <- fir_nodelay(A, nf, fc / (fs / 2))$y
  M <- fir_nodelay(M, nf, fc / (fs / 2))$y
  W <- body_axes(A, M)
  X <- t(drop(W[, 1, ]))
#additional function --------------------------------------
  cumsum_mat <- function(mat){
    a <- matrix(0, ncol = ncol(mat), nrow = nrow(mat))
    for(i in 1:ncol(mat)){
      a[,i] <- cumsum(mat[,i])
    }
    return(a)
  }
#----------------------------------------------------------  
  if(is.matrix(X)){
    T <- cumsum_mat((s / fs) * X)
  }
  else{
    T <- cumsum((s / fs) * X)
  }
  if (include_pe == TRUE) {
    pitch <- a2pr(A,fs,fc)$p
    if(is.matrix(pitch)){
      pe <- -cumsum_mat((s / fs) * sin(pitch))
    }
    else{
      pe <- -cumsum((s / fs) * sin(pitch))
    }
    return(list(T = T, pe = pe))
  } 
  return(T)
}
