---
title: "Peak Detection"
author: "David Sweeney"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Peak Detection}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```{r, include = FALSE}
require(tagtools)
```

Introduction
---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Scientists have long struggled to study animal behavior without imposing stress upon the animal being observed (Brown et al. 2013; Schneirla 1950). Scientists have also found it difficult to make visual observations of animals in environments and times periods that are relatively inaccessible to most humans (Allen et al. 2016). Out of these two concerns arose the scientific field of biotelemetry (Kooyman 2003).  Since the first use of tagging devices on animals in 1963, the field of biotelemtery has evolved into a discipline that allows for the detailed behavioral studying of animals ranging in size from chipmunks to blue whales (Hammond et al. 2016; Acevedo-Gutiérrez et al. 2002; Kooyman 2003).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The field of marine biotagging has become one of the most prominent fields of biotelemetry. A variety of unique tagging systems (i.e. DTAGs, Acousonde tags, etc.) have been developed by researchers around the world to gain non-invasive access to the unique lives of marine creatures (Johnson and Tyack 2003; Burgess et al. 1998). From the data obtained from these tags, scientists are able to determine the exact moment in time when an animal exhibited a certain behavior (Johson et al. 2009; Goldbogen et al. 2006; Goldbogen et al. 2008; Miller et al. 2004). However, due to the often high sampling rate of multisensor tags and the long duration of recording, the process of determining the time of a given behavior can be quite laborious and time consuming.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In a quest to make data analysis more efficient, scientists have begun to develope software functions which automatically detect animal behaviors from multisensor data (Owen et al. 2016; Allen et al. 2016; Doniol-Valcroze et al. 2011; Kokubun et al. 2011; Cox et al. 2017; Ware et al. 2011; Viviant et al. 2010). All of these functions scan through data searching for signal characteristics which are known to be indicators of unique animal behaviors. Despite he conceptual simplicity of these behavior detectors, the creation and application of these functions is full of difficulties and imperfections. First of all, despite the careful design of these functions, none of them possess 100% accuracy in detecting the behavior desired. They all struggle with false detections and missed detections. Also, these functions do not allow for the detection of a wide range of behaviors. They are instead used on data from a specific type of animal and look for a specific type of behavior. Finally, these detectors require the user to input a certain type of data, into the function, which may only be accessed through a certain software program. This may cause difficulties for researchers who wish to use a function for a similar purpose but do not possess the necessary data type/format or software.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In light of these logistical difficulties, we have developed a function, usable in three widely used software programs (R, Matlab, and Octave), which is generalizable to a wide variety of data types/formats, animals, and behaviors. The function, called detect_peaks, is a part of the tagtools package in R.

Function Design
---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The detect_peaks function contains 6 specified inputs and allows for additional inputs to be added at the end of the command: 
```
detect_peaks(data, sr, FUN = NULL, thresh = NULL, bktime = NULL, plot_peaks = NULL,...)
```
I will <b>not</b> be explaining exactly what each input does in this vignette (for this, see the help file within the package). Instead, I am going to describe what the user needs to decide before using this function and the thought process behind each significant step in the function script. Later on, in the section titled "Case Study", I will walk through a specific example in which the function may be used.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In order to make the best use of this function, it is helpful to understand a few things regarding the design of this function. First of all, as the name of the function suggests, this function determines the time of an animal behavior by going through large data sets and locating large spikes/peaks in the data signal. A peak is determined to represent a behavior event if it surpasses a predetermined threshold. Robert Urick, in his book <i>Principles of Underwater Sound for Engineers</i>, describes a threshold as being something which, "when it is exceeded, the decision "[behavior event] present" will be made" (Urick 1967). In this function, the default threshold level (input "thresh") is set to be the 0.99 quantile of the signal. However, this threshold level will not be appropriate for all circumstances. There may be cases in which this threshold level will bring many false positive (peak detected without a present behavior) detections or not enough true positive (peak detected with a present behavior) detections. Typically, if the thrshold is too high, the number of missed detections be higher and only the strongest peaks representing behavior events will be detected. If the threshold is too low, the number of true positive detections will be higher, but so will the number of false positives (Urick 1967). Therefore, we allow the user to change the threshold level if they desire a level other than the default (more information about setting a proper threshold level can be found in the section "ROC Curves").

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Once the peaks in the signal have been detected, the blanking time (input "bktime") is used to determine the start and end times of each peak as well as the time at which the peak reached a maximum level in the signal. The default value for the blanking time is five seconds of data (determine by 5 * "sr"). The first job of the blanking time is to determine if adjacent peaks represent one of multiple behavior events. The blanking time is an amount of time within which all detected peaks are determined to represent one large unified behavior event. All detected peaks separated by a length of time larger than the blanking time are considered unique behavior events. At this point, start times (point at which the peak first exceeds the threshold), end times (point at which the peak finally receeds beneath the threshold value), start time (point at which the peak reaches a maximum signal strength), and peak maximum (maximum value of the detected peak in the same units as the signal) are determined and returned to the user.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; After the function has finished running, the signal being studied is plotted (assuming the input for "plot_peaks" is TRUE) with each determined peak labeled by a marker. At this point, the user is able to examine the quality of the functions performace at detecting true positive peaks. If the user determines that he/she wishes for the threshold level or the blanking time to be altered, the user is able to click on the graph to change these values. For example, if the user wants to change only the threshold level, he/she can click once within the plot at the given threshold level desired and click "Finish". This will rerun the function and return new peak detections and a new plot. If the user only wants to change the blanking time, he/she must click twice within the plot and then click "Finish". The distance between each click is determines the new blanking time and the function is rerun. If the user wants to change both the threshold and the blanking time, the user must click three times. The first click is to change the threshold and the second two clicks are to alter the blanking time. After clicking three times, the function is rerun. For the occassion when the user is satisfied with the threshold and blanking times used in the first run of the function, the user must simply click the "Finish" button located just above the plot, and peak detections will be returned to the user. Along with the peak detections, the user will also always receive the threshold level and blanking time used in the analysis.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The final, and perhaps most crucial thing to understand before using this function, is that the input for "data" can be either a signal vector or a matrix of data. If the data is a signal vector which the user wishes to have peaks detected from, nothing should be given for the input "FUN". However, if the data given to the input is a matrix, an input for "FUN" must be given as the peak detector is not able to detect peaks from matrix data. The input for "FUN" is any other function which the user wishes to use in manipulating the matrix into a signal vector (which then passes through the peak detection process as descibed above). Examples from the tagtools package are njerk, odba, etc., but the function does not have to be from within this package. when specifying the function to be used within detect_peaks, the user must make sure to surround the input for "FUN" in quotation marks. I will provide examples of how this function works for both vector and matrix inputs in the section "Case Study" below.

Case Study
---
###Example 1
