%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Stacy DeRuiter\Dropbox\TagTools\Practicals\zc_dives.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/03 16:54:23

%% Initialize variables.
filename = 'C:\Users\Stacy DeRuiter\Dropbox\TagTools\Practicals\zc_dives.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: categorical (%C)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%C%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
zcdives = table(dataArray{1:end-1}, 'VariableNames', {'whale_num','whale_ID','dive_num','dive_type','descent_dur','ascent_dur','descent_rate','ascent_rate','dive_dur','post_dive_surf','t_to_click','click_dur','fluke_rate','odba','max_depth','head_var'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;