<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Data quality &amp; error correction • tagtools</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Data quality &amp; error correction">
<meta property="og:description" content="tagtools">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">tagtools</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="data-quality-error-correction_files/header-attrs-2.9/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Data quality &amp; error correction</h1>
                        <h4 class="author">tagtools project team</h4>
            
            <h4 class="date">2021-07-28</h4>
      
      
      <div class="hidden name"><code>data-quality-error-correction.Rmd</code></div>

    </div>

    
    
<p>Welcome to the <code>data-quality-error-correction</code> vignette! Thanks for taking some time to get to know our package. We hope you’re enjoying yourself.</p>
<p>This vignette deals with how to check data quality for accelerometers and magnetometers, as well as how to make corrections for some common sources of error.</p>
<p><em>Estimated time for this practical: 25 minutes</em></p>
<p>These vignettes assume that you have R/Rstudio installed on your machine, some basic experience working with them, and can execute provided code, making some user-specific changes along the way (e.g. to help R find a file you downloaded). We will provide you with quite a few lines. To boost your own learning, you would do well to try and write them before opening what we give, using this just to check your work.</p>
<p>Additionally, be careful when copy-pasting special characters such as _underscores_ and ‘quotes’. If you get an error, one thing to check is that you have just a single, simple underscore, and <code>'straight quotes'</code>, whether <code>'single'</code> or <code>"double"</code> (rather than “smart quotes”).</p>
<div id="checking-accelerometer-and-magnetometer-data" class="section level1">
<h1 class="hasAnchor">
<a href="#checking-accelerometer-and-magnetometer-data" class="anchor"></a>Checking accelerometer and magnetometer data</h1>
<p>Biologging data are not always ready-to-use when you read them off the tag. Some corrections may be needed. Quality checking is fairly easy for pressure data from aquatic mammals because we know they will breathe at the surface. Data from accelerometers and magnetometers are more difficult. For one thing, there are three axes, and also we don’t have such an intuitive feel for what they should look like. However, fortunately, there are some quality checks we can do with <code>A</code> and <code>M</code> data that help to catch and correct problems.</p>
<p>Our objective here is to estimate the orientation of an animal (its pitch, roll and heading) as a function of time. To do so we first need to check and correct errors in <code>A</code> and <code>M</code>.</p>
<div id="data-quality-checks" class="section level2">
<h2 class="hasAnchor">
<a href="#data-quality-checks" class="anchor"></a>Data quality checks</h2>
<p>For this practical we will use data from a tag attached to the back of a sperm whale. This dataset is built into the <code>tagtools</code> package, so you can access it using <code>system.file</code>.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">tagtools</span><span class="op">)</span>
<span class="va">sw_file_path</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/system.file.html">system.file</a></span><span class="op">(</span><span class="st">"extdata"</span>, <span class="st">"rawtestset3.nc"</span>, package <span class="op">=</span> <span class="st">"tagtools"</span>, mustWork <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">sw</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/load_nc.html">load_nc</a></span><span class="op">(</span><span class="va">sw_file_path</span><span class="op">)</span></code></pre></div>
<p>Look at the overall structure to get an idea of how the data are stored, and check out the info structure to see where the data came from.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">sw</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">sw</span><span class="op">$</span><span class="va">info</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#inspect_sw">
Show/Hide Results
</button>
<div id="inspect_sw" class="collapse">
<pre><code>#&gt; [1] "results for `str(sw, max.level = 1)`:"
#&gt; [1] "-------------------------------------"
#&gt; List of 5
#&gt;  $ _empty:List of 1
#&gt;  $ P     :List of 16
#&gt;  $ A     :List of 18
#&gt;  $ M     :List of 18
#&gt;  $ info  :List of 36
#&gt;  - attr(*, "class")= chr [1:2] "animaltag" "list"
#&gt; [1] "-------------------------------------"
#&gt; [1] "and results for `sw$info`:"
#&gt; [1] "-------------------------------------"
#&gt; $depid
#&gt; [1] "sw03_165a"
#&gt; 
#&gt; $dtype_source
#&gt; [1] "sw03_165aprh.mat,sw03_165aaud.txt"
#&gt; 
#&gt; $dtype_datetime_made
#&gt; [1] "18/07/2017 22:15:00"
#&gt; 
#&gt; $dtype_nfiles
#&gt; [1] "1"
#&gt; 
#&gt; $dtype_format
#&gt; [1] "MAT"
#&gt; 
#&gt; $device_serial
#&gt; [1] ""
#&gt; 
#&gt; $device_make
#&gt; [1] "DTAG"
#&gt; 
#&gt; $device_type
#&gt; [1] "Archival"
#&gt; 
#&gt; $device_model
#&gt; [1] "DTAG2"
#&gt; 
#&gt; $device_url
#&gt; [1] "https://www.soundtags.org"
#&gt; 
#&gt; $sensors_firm
#&gt; [1] "Not specified"
#&gt; 
#&gt; $sensors_soft
#&gt; [1] "Not specified"
#&gt; 
#&gt; $sensors_list
#&gt; [1] "3axis Accelerometer,3 axis Magnetometer,Pressure,Sound"
#&gt; 
#&gt; $animal_id
#&gt; [1] "Unknown"
#&gt; 
#&gt; $animal_species_common
#&gt; [1] "Sperm whale"
#&gt; 
#&gt; $animal_species_science
#&gt; [1] "Physeter macrocephalus"
#&gt; 
#&gt; $animal_dbase_url
#&gt; [1] "http://www.arkive.org/sperm-whale/physeter-macrocephalus/"
#&gt; 
#&gt; $animal_dbase_itis
#&gt; [1] "180488"
#&gt; 
#&gt; $dephist_device_tzone
#&gt; [1] "0"
#&gt; 
#&gt; $dephist_device_regset
#&gt; [1] "dd/mm/yyyy HH:MM:SS"
#&gt; 
#&gt; $dephist_device_datetime_start
#&gt; [1] "2003-06-14 18:38:35"
#&gt; 
#&gt; $dephist_deploy_locality
#&gt; [1] "northern Gulf of Mexico"
#&gt; 
#&gt; $dephist_deploy_location_lat
#&gt; [1] "28.48"
#&gt; 
#&gt; $dephist_deploy_location_lon
#&gt; [1] "-89.052"
#&gt; 
#&gt; $dephist_deploy_datetime_start
#&gt; [1] "2003-06-14 18:38:35"
#&gt; 
#&gt; $dephist_deploy_method
#&gt; [1] "Suction cups"
#&gt; 
#&gt; $project_name
#&gt; [1] "GOM 2003"
#&gt; 
#&gt; $project_datetime_start
#&gt; [1] "2003-06-03"
#&gt; 
#&gt; $project_datetime_end
#&gt; [1] "2003-06-24"
#&gt; 
#&gt; $provider_name
#&gt; [1] "Mark Johnson"
#&gt; 
#&gt; $provider_details
#&gt; [1] "Univ St Andrews"
#&gt; 
#&gt; $provider_email
#&gt; [1] "info@animaltags.org"
#&gt; 
#&gt; $provider_license
#&gt; [1] "Contact data provider"
#&gt; 
#&gt; $provider_cite
#&gt; [1] "Contact data provider"
#&gt; 
#&gt; $provider_doi
#&gt; [1] "Contact data provider"
#&gt; 
#&gt; $creation_date
#&gt; [1] "02-Dec-2019 16:14:58"</code></pre>
</div>
<p>Inspect the depth, acceleration and magnetometer data with <code>plott</code>:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/plott.html">plott</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>depth <span class="op">=</span> <span class="va">sw</span><span class="op">$</span><span class="va">P</span>, acc <span class="op">=</span> <span class="va">sw</span><span class="op">$</span><span class="va">A</span>, mag <span class="op">=</span> <span class="va">sw</span><span class="op">$</span><span class="va">M</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#plott_sw">
Show/Hide Results
</button>
<div id="plott_sw" class="collapse">
<p><img src="data-quality-error-correction_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
</div>
<p>Depth, <code>sw$P</code>, seems fine—it looks like a depth versus time plot for a diving whale. However, it is hard to see whether there are any problems with accelerometer and magnetometer data, <code>sw$A</code> and <code>sw$M</code>, from their respective plots. Two things can often go wrong with raw tag data:</p>
<ul>
<li>the sensors may not be well-calibrated, and</li>
<li>the axes of <code>A</code> and <code>M</code> may not be aligned with the animal’s axes.</li>
</ul>
<p>Luckily, we can check both of these from the data.</p>
<p>When there is not much specific acceleration, the vector magnitude of each acceleration measurement should be close to the magnitude of the gravity vector, i.e., 9.8 <span class="math inline">\(\frac{m}{s^2}\)</span>.</p>
<p>The magnetometer data should also have fairly constant vector magnitude equal to the field strength where the data came from. It should be about 48 <span class="math inline">\(\mu\)</span>T in this case since the tag was deployed at <span class="math inline">\(28.48^{\circ}\)</span>, <span class="math inline">\(-89.052^{\circ}\)</span> latitude/longitude. (That is, <span class="math inline">\(28.48^{\circ}\)</span> north latitude, <span class="math inline">\(89.052^{\circ}\)</span> west longitude.)</p>
<p><em>(A useful website to find the geomagnetic field parameters, based on where your tag is deployed from, is: <a href="https://www.ngdc.noaa.gov/geomag-web/#igrfwmm" class="uri">https://www.ngdc.noaa.gov/geomag-web/#igrfwmm</a>.)</em></p>
<p>Finally, the angle between <code>A</code> and <code>M</code> should be close to the magnetic inclination angle, which is also locally constant, <span class="math inline">\(59^{\circ}\)</span> in this case.</p>
<p>Use <code><a href="../reference/check_AM.html">check_AM()</a></code> to compute the field strength of <code>A</code> and <code>M</code> and their inclination angle. Recall that A is stored as <code>sw$A</code> and M is stored as <code>sw$M</code>, and write the result to a new object <code>AMcheck</code> or another similar name. Then check out what this object contains.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">AMcheck</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/check_AM.html">check_AM</a></span><span class="op">(</span><span class="va">sw</span><span class="op">$</span><span class="va">A</span>, <span class="va">sw</span><span class="op">$</span><span class="va">M</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">AMcheck</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#str_AMcheck">
Show/Hide Results
</button>
<div id="str_AMcheck" class="collapse">
<pre><code>#&gt; List of 2
#&gt;  $ fstr: num [1:71975, 1:2] 9.76 9.62 9.39 9.32 9.31 ...
#&gt;  $ incl: num [1:71975, 1] -0.655 -0.634 -0.62 -0.577 -0.529 ...</code></pre>
</div>
<p>You should be able to tell AMcheck is a list containing two vectors, <code>AMcheck$fstr</code> (field strength) and <code>AMcheck$incl</code> (inclination). Open the next code to see how we plott these.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sampling_rate</span> <span class="op">&lt;-</span> <span class="va">sw</span><span class="op">$</span><span class="va">A</span><span class="op">$</span><span class="va">sampling_rate</span> <span class="co"># get the sampling rate of A and M for plotting</span>
<span class="co"># plott fstr, and incl (converting from radians to degrees)</span>
<span class="fu"><a href="../reference/plott.html">plott</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>fstr <span class="op">=</span> <span class="va">AMcheck</span><span class="op">$</span><span class="va">fstr</span>, incl <span class="op">=</span> <span class="va">AMcheck</span><span class="op">$</span><span class="va">incl</span><span class="op">*</span><span class="fl">180</span><span class="op">/</span><span class="va">pi</span><span class="op">)</span>, fsx <span class="op">=</span> <span class="va">sampling_rate</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#plott_AMcheck">
Show/Hide Results
</button>
<div id="plott_AMcheck" class="collapse">
<p><img src="data-quality-error-correction_files/figure-html/unnamed-chunk-9-1.png" width="700"></p>
</div>
<p>The top plot shows the field strength of <code>A</code> and <code>M</code>. These should be close to 9.8 and 48, respectively, with little variation. If not, the acceleration or magnetometer data need re-calibration. Usually, the problem is with <code>M</code> and is due to stray magnetic fields in the tag. Fix this by doing a ‘hard-iron correction’, which the function <code>fix_offset_3d</code> can do.</p>
<p>Again, recall that <code>M</code> is stored within <code>sw</code> as <code>sw$M</code>. Write the result as an object <code>Mf</code>, then look at what <code>Mf</code> contains.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Mf</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/fix_offset_3d.html">fix_offset_3d</a></span><span class="op">(</span><span class="va">sw</span><span class="op">$</span><span class="va">M</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">Mf</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#str_Mf">
Show/Hide Results
</button>
<div id="str_Mf" class="collapse">
<pre><code>#&gt; List of 2
#&gt;  $ X:List of 19
#&gt;  $ G:List of 1</code></pre>
</div>
<p>This should show you that Mf is itself a list with two elements, <code>Mf$X</code> and <code>Mf$G</code>. Comparing <code>Mf$G</code> and <code>Mf$X</code> with <code>sw$A</code>,</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">Mf</span><span class="op">$</span><span class="va">G</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">Mf</span><span class="op">$</span><span class="va">X</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">sw</span><span class="op">$</span><span class="va">A</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#str_MfGXswA">
Show/Hide Results
</button>
<div id="str_MfGXswA" class="collapse">
<pre><code>#&gt; [1] "----------------"
#&gt; [1] "results for Mf$G"
#&gt; [1] "----------------"
#&gt; List of 1
#&gt;  $ poly: num [1:3, 1:2] 1 1 1 9.64 -5.58 ...
#&gt; [1] "----------------"
#&gt; [1] "results for Mf$X"
#&gt; [1] "----------------"
#&gt; List of 19
#&gt;  $ data              : num [1:71975, 1:3] -28.6 -28.1 -27.4 -26.6 -25.6 ...
#&gt;  $ sampling          : chr "regular"
#&gt;  $ sampling_rate     : num 5
#&gt;  $ sampling_rate_unit: chr "Hz"
#&gt;  $ depid             : chr "sw03_165a"
#&gt;  $ creation_date     : chr "07-Aug-2017 15:32:56"
#&gt;  $ history           : chr "fix_offset_3d"
#&gt;  $ type              : chr "mag"
#&gt;  $ full_name         : chr "Magnetometer"
#&gt;  $ description       : chr "triaxial magnetometer"
#&gt;  $ unit              : chr "uT"
#&gt;  $ unit_name         : chr "micro Tesla"
#&gt;  $ unit_label        : chr "\\muT"
#&gt;  $ start_offset      : num 0
#&gt;  $ start_offset_units: chr "second"
#&gt;  $ column_name       : chr "x,y,z"
#&gt;  $ frame             : chr "sensor"
#&gt;  $ axes              : chr "FRU"
#&gt;  $ cal_poly          : num [1:3, 1:2] 1 1 1 9.64 -5.58 ...
#&gt; [1] "----------------"
#&gt; [1] "results for sw$A"
#&gt; [1] "----------------"
#&gt; List of 18
#&gt;  $ data              : num [1:71975, 1:3] -3.49 -3.32 -3.04 -2.89 -2.73 ...
#&gt;  $ sampling          : chr "regular"
#&gt;  $ sampling_rate     : num 5
#&gt;  $ sampling_rate_unit: chr "Hz"
#&gt;  $ depid             : chr "sw03_165a"
#&gt;  $ creation_date     : chr "07-Aug-2017 15:32:56"
#&gt;  $ history           : chr "sens_struct,decdc(5)"
#&gt;  $ type              : chr "acc"
#&gt;  $ full_name         : chr "Acceleration"
#&gt;  $ description       : chr "triaxial acceleration"
#&gt;  $ unit              : chr "m/s2"
#&gt;  $ unit_name         : chr "meters per seconds squared"
#&gt;  $ unit_label        : chr "m/s^2"
#&gt;  $ start_offset      : num 0
#&gt;  $ start_offset_units: chr "second"
#&gt;  $ column_name       : chr "x,y,z"
#&gt;  $ frame             : chr "tag"
#&gt;  $ axes              : chr "FRU"</code></pre>
</div>
<p>you’ll notice that <code>Mf$X</code> and <code>sw$A</code> structures contain the same kind of data. Hence <code>Mf$X</code> can stand in for <code>sw$M</code> (<code>Mf</code> by itself cannot). So, try and re-run <code><a href="../reference/check_AM.html">check_AM()</a></code> with <code>sw$A</code> and <code>Mf$X</code> to see if the field strength has improved.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">AMcheck2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/check_AM.html">check_AM</a></span><span class="op">(</span><span class="va">sw</span><span class="op">$</span><span class="va">A</span>, <span class="va">Mf</span><span class="op">$</span><span class="va">X</span><span class="op">)</span>
<span class="fu"><a href="../reference/plott.html">plott</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>fstr <span class="op">=</span> <span class="va">AMcheck2</span><span class="op">$</span><span class="va">fstr</span>, incl <span class="op">=</span> <span class="va">AMcheck2</span><span class="op">$</span><span class="va">incl</span><span class="op">*</span><span class="fl">180</span><span class="op">/</span><span class="va">pi</span><span class="op">)</span>, fsx <span class="op">=</span> <span class="va">sampling_rate</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#plott_AMcheck2">
Show/Hide Results
</button>
<div id="plott_AMcheck2" class="collapse">
<p><img src="data-quality-error-correction_files/figure-html/unnamed-chunk-15-1.png" width="700"></p>
</div>
<p>If all has gone well, your field strength should be pretty constant at right around 48 <span class="math inline">\(\mu\)</span>T. Is it? Great work!</p>
<p>Now look again at the inclination angle (bottom plot). Chances are, it doesn’t look consistently close to <span class="math inline">\(59^{\circ}\)</span>. Therefore, we need to do the next step…</p>
</div>
<div id="correcting-the-axes-of-triaxial-sensor-data" class="section level2">
<h2 class="hasAnchor">
<a href="#correcting-the-axes-of-triaxial-sensor-data" class="anchor"></a>Correcting the axes of triaxial sensor data</h2>
<p>If the field strength is okay for <code>A</code> and <code>M</code> but the inclination angle is wrong, this is a strong indication that the magnetometer and accelerometer axes don’t match. Assuming that the accelerometer axes are correct, I found by trial and error that the magnetometer axes are mapped as follows:</p>
<table class="table">
<colgroup>
<col width="19%">
<col width="15%">
</colgroup>
<thead><tr class="header">
<th align="center">Sensor.axis</th>
<th align="center">Tag.axis</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">x</td>
<td align="center">-x</td>
</tr>
<tr class="even">
<td align="center">y</td>
<td align="center">z</td>
</tr>
<tr class="odd">
<td align="center">z</td>
<td align="center">y</td>
</tr>
</tbody>
</table>
<p>You could make these corrections to <code>Mf</code> one-by-one, but it is probably more convenient to do them all at once. To make this happen, define a ‘map’ matrix that summarizes the changes:</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Map</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>,
                <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>,
                <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>,
              nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">3</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#Map_matrix">
Show/Hide Results
</button>
<div id="Map_matrix" class="collapse">
<pre><code>#&gt;      [,1] [,2] [,3]
#&gt; [1,]   -1    0    0
#&gt; [2,]    0    0    1
#&gt; [3,]    0    1    0</code></pre>
</div>
<p>Use function <code><a href="../reference/rotate_vecs.html">rotate_vecs()</a></code> to apply <code>Map</code> to <code>Mf$X</code> and make a new ‘tag frame’ data structure:</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Mt</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rotate_vecs.html">rotate_vecs</a></span><span class="op">(</span><span class="va">Mf</span><span class="op">$</span><span class="va">X</span>,<span class="va">Map</span><span class="op">)</span></code></pre></div>
<p><code>Mt</code> is now oriented in the tag’s frame of reference. Add this important information about <code>Mt</code> into the structure <code>Mt</code>:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Mt</span><span class="op">$</span><span class="va">frame</span> <span class="op">&lt;-</span> <span class="st">'tag'</span>
<span class="va">Mt</span><span class="op">$</span><span class="va">sensor_map</span> <span class="op">&lt;-</span> <span class="va">Map</span>        <span class="co"># save the Map matrix too</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">Mt</span>, max.level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#Mt_frameNmap">
Show/Hide Results
</button>
<div id="Mt_frameNmap" class="collapse">
<pre><code>#&gt; List of 20
#&gt;  $ data              : num [1:71975, 1:3] 28.6 28.1 27.4 26.6 25.6 ...
#&gt;  $ sampling          : chr "regular"
#&gt;  $ sampling_rate     : num 5
#&gt;  $ sampling_rate_unit: chr "Hz"
#&gt;  $ depid             : chr "sw03_165a"
#&gt;  $ creation_date     : chr "07-Aug-2017 15:32:56"
#&gt;  $ history           : chr "fix_offset_3d"
#&gt;  $ type              : chr "mag"
#&gt;  $ full_name         : chr "Magnetometer"
#&gt;  $ description       : chr "triaxial magnetometer"
#&gt;  $ unit              : chr "uT"
#&gt;  $ unit_name         : chr "micro Tesla"
#&gt;  $ unit_label        : chr "\\muT"
#&gt;  $ start_offset      : num 0
#&gt;  $ start_offset_units: chr "second"
#&gt;  $ column_name       : chr "x,y,z"
#&gt;  $ frame             : chr "tag"
#&gt;  $ axes              : chr "FRU"
#&gt;  $ cal_poly          : num [1:3, 1:2] 1 1 1 9.64 -5.58 ...
#&gt;  $ sensor_map        : num [1:3, 1:3] -1 0 0 0 0 1 0 1 0</code></pre>
</div>
<p>Check the field strength and inclination of <code>sw$A</code> and <code>Mt</code> once more. Try and do this on your own, then check your work with the code below: write a new object, perhaps <code>AMcheck3</code>, with the result of check_AM on <code>sw$A</code> and <code>Mt</code>. Then use your new object <code>AMcheck3</code> in place of <code>AMcheck2</code> to get the same two plots, but with the newly corrected data.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">AMcheck3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/check_AM.html">check_AM</a></span><span class="op">(</span><span class="va">sw</span><span class="op">$</span><span class="va">A</span>, <span class="va">Mt</span><span class="op">)</span>
<span class="fu"><a href="../reference/plott.html">plott</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>fstr <span class="op">=</span> <span class="va">AMcheck3</span><span class="op">$</span><span class="va">fstr</span>, incl <span class="op">=</span> <span class="va">AMcheck3</span><span class="op">$</span><span class="va">incl</span><span class="op">*</span><span class="fl">180</span><span class="op">/</span><span class="va">pi</span><span class="op">)</span>, fsx <span class="op">=</span> <span class="va">sampling_rate</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#plott_AMcheck3">
Show/Hide Results
</button>
<div id="plott_AMcheck3" class="collapse">
<p><img src="data-quality-error-correction_files/figure-html/unnamed-chunk-23-1.png" width="700"></p>
</div>
<p>Are we good? Bear in mind that the inferred inclination angle from accelerometer and magnetometer data is usually a bit noisy so don’t expect <code>incl</code> to be exactly on the expected inclination angle. It should get pretty close, though (around <span class="math inline">\(59^{\circ}\)</span>).</p>
<p>When you are comfortable that the data pass the quality checks, save them to a new NetCDF file:</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/save_nc.html">save_nc</a></span><span class="op">(</span><span class="st">'testset3_tag_frame'</span>, X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">sw</span><span class="op">$</span><span class="va">A</span>, <span class="va">Mt</span>, <span class="va">sw</span><span class="op">$</span><span class="va">P</span>, <span class="va">sw</span><span class="op">$</span><span class="va">info</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<!--Sam: this is the one part that still really doesn't work. Screenshot June 2, 10:33am. -->
<p>The corrections that you made to get <code>Mt</code> are stored in its structure so this information will also be saved automatically in your nc file - verify this by showing the contents of <code>Mt</code>.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">Mt</span><span class="op">)</span></code></pre></div>
<button class="btn btn-primary" data-toggle="collapse" data-target="#str_Mt">
Show/Hide Results
</button>
<div id="str_Mt" class="collapse">
<pre><code>#&gt; List of 20
#&gt;  $ data              : num [1:71975, 1:3] 28.6 28.1 27.4 26.6 25.6 ...
#&gt;  $ sampling          : chr "regular"
#&gt;  $ sampling_rate     : num 5
#&gt;  $ sampling_rate_unit: chr "Hz"
#&gt;  $ depid             : chr "sw03_165a"
#&gt;  $ creation_date     : chr "07-Aug-2017 15:32:56"
#&gt;  $ history           : chr "fix_offset_3d"
#&gt;  $ type              : chr "mag"
#&gt;  $ full_name         : chr "Magnetometer"
#&gt;  $ description       : chr "triaxial magnetometer"
#&gt;  $ unit              : chr "uT"
#&gt;  $ unit_name         : chr "micro Tesla"
#&gt;  $ unit_label        : chr "\\muT"
#&gt;  $ start_offset      : num 0
#&gt;  $ start_offset_units: chr "second"
#&gt;  $ column_name       : chr "x,y,z"
#&gt;  $ frame             : chr "tag"
#&gt;  $ axes              : chr "FRU"
#&gt;  $ cal_poly          : num [1:3, 1:2] 1 1 1 9.64 -5.58 ...
#&gt;  $ sensor_map        : num [1:3, 1:3] -1 0 0 0 0 1 0 1 0</code></pre>
</div>
<p>Your processing steps are listed in the ‘history’ field and so are traceable as you would expect in a professional archive.</p>
</div>
</div>
<div id="review" class="section level1">
<h1 class="hasAnchor">
<a href="#review" class="anchor"></a>Review</h1>
<p>What have you learned? A few powerful tools for detecting and correcting common errors in raw data.</p>
<p>Great work! You’ve completed this vignette.</p>
<p><em>If you’d like to continue working through these vignettes, <code>tag-to-whale-frame</code> is probably a good option. It deals with estimating and correcting the orientation of a tag on an animal. This vignette will use tag data that </em>are not <em>aligned to the animal’s body axes, e.g., because the tag was applied to a free-moving whale.</em></p>
<hr>
<p>Animaltags home pages: <a href="http://animaltags.org/" class="uri">http://animaltags.org/</a> (old), <a href="https://animaltags.netlify.app/" class="uri">https://animaltags.netlify.app/</a> (new), <a href="https://github.com/stacyderuiter/TagTools" class="uri">https://github.com/stacyderuiter/TagTools</a> (for source code)</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Stacy DeRuiter.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
