---
title: "Notes on interactive PRHpred figures"
author: "SDR"
date: "11/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes working on prh_predictor1
make sure there are user options to:
   - Quit
   - zoom in and out
   - show values on plot if hover
   - remove this dive/don't use and advance to next
   - case "e" (edit by calling up other figure for this point)
  
  if shiny would it work?
  click on a point in main plot to choose what is shown in 2nd plot.
  have button for: delete selected; be able to zoom in/out (plotly?)
  have tab for results print out
  in one-dive tab, have zoom in/out; brush to select an area and buttons for "set as window 1" and "set as 2"?
  could use plotly to have multi-panels with right zoom, etc.
  BUT would need to upload data to get it in and download it to get it out
  and user would have to do manually?
  
  simplest version: click on one to edit
  use getGraphicsEvent() to handle different options!!
  should be able to make same as Mark's.
  