---
title: "WMMC Work"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task and Priority List
Ordered by priority within task types.

TO DO FRIDAY

matlab version of prac and to Lucia

why is dephist start time saving in NC file as a number? change to character...
I think it is fixed by as.character(), need to check.

Need to re-run all and check for further bugs.
### R scripts

#### Analysis

- find_dives: results not identical in matlab/R?

#### Data IO

- read cats
- read dtag
- read daily diary
- read little leo

#### Interactive vis

- "audit"

#### Other

- fix_3d
- fix_offset_pressure
- residence_index
- rms_track

- check for other files with changes?
- check for body_axes() used in other functions?
(sound)
get_audio
spec2tol
wavseq_read

### animaltags.org

- Confirm that ftp works
- Set up template site for this workshop/links/filestorage

### Lectures and Practicals

#### 1. Intro/ IO with prac

#### 2. Tracks, detectors, and stats (no prac)